// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUqevuZQ1iM5i8KzZ1nQRHZf8rAlQAyHQ',
    appId: '1:440818556775:web:9857bc36d48d04dde499c2',
    messagingSenderId: '440818556775',
    projectId: 'deeptalks-1ab0f',
    authDomain: 'deeptalks-1ab0f.firebaseapp.com',
    storageBucket: 'deeptalks-1ab0f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_UnRbyjPfA4QQaab7ElRe8u8fgnJpsq8',
    appId: '1:440818556775:android:bc63d40504a9a6f6e499c2',
    messagingSenderId: '440818556775',
    projectId: 'deeptalks-1ab0f',
    storageBucket: 'deeptalks-1ab0f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACLz3WFzXmk4MgQIeKQjM3dwNg8xmGTc0',
    appId: '1:440818556775:ios:5673b295c6e00185e499c2',
    messagingSenderId: '440818556775',
    projectId: 'deeptalks-1ab0f',
    storageBucket: 'deeptalks-1ab0f.firebasestorage.app',
    iosBundleId: 'com.example.deeptalks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACLz3WFzXmk4MgQIeKQjM3dwNg8xmGTc0',
    appId: '1:440818556775:ios:5673b295c6e00185e499c2',
    messagingSenderId: '440818556775',
    projectId: 'deeptalks-1ab0f',
    storageBucket: 'deeptalks-1ab0f.firebasestorage.app',
    iosBundleId: 'com.example.deeptalks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUqevuZQ1iM5i8KzZ1nQRHZf8rAlQAyHQ',
    appId: '1:440818556775:web:310bcf137434d8e6e499c2',
    messagingSenderId: '440818556775',
    projectId: 'deeptalks-1ab0f',
    authDomain: 'deeptalks-1ab0f.firebaseapp.com',
    storageBucket: 'deeptalks-1ab0f.firebasestorage.app',
  );
}
